import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useStore } from 'store/index'

export default function Home() {
  const store = useStore()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {store.userInfo.nickname}
    </div>
  )
}
